# Copyright (c) 2024-2026 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# Based on js-checks.yml but using pnpm instead of npm

name: JS Checks with pnpm

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: Number of commits to fetch. 0 indicates all history for all branches and tags.
        default: 1
        type: number
      node-versions:
        description: Array of Node versions to test with (JSON string)
        default: "['']"
        type: string

jobs:
  run-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
      - uses: hemilabs/actions/setup-node-env@42a939f90638fa4c3f3820dbb9a3cdd8404a2590
        with:
          package-manager: pnpm
      - run: pnpm run --if-present format:check
      - run: pnpm run --if-present lint
      - run: pnpm run --if-present deps:check
      - run: pnpm run --if-present --recursive build
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
      - uses: hemilabs/actions/setup-node-env@42a939f90638fa4c3f3820dbb9a3cdd8404a2590
        with:
          node-version: ${{ matrix.node-version }}
          package-manager: pnpm
      - run: pnpm run --if-present --recursive test
    strategy:
      matrix:
        node-version: ${{ fromJSON(inputs.node-versions) }}
